/**
 * These will the url paths for the client frontend
 */
export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  productDetail: '/product/detail',
  privacyPolicy: '/privacy-policy',
  termsAndConditions: '/terms-and-conditions',
  returnPolicy: '/return-policy',
  shippingPolicy: '/shipping-policy',
};

/**
 * These will the url paths for the admin frontend
 */
export const dashboardRoutes = {
  dashboard: '/dashboard',
  roles: '/dashboard/roles',
  productCategories: '/dashboard/product-category',
  productInterests: '/dashboard/product-interest',
  productAges: '/dashboard/product-age',
  products: '/dashboard/products',
  reviews: '/dashboard/reviews',
  dealOfTheDay: '/dashboard/deal-of-the-day',
  bestSellers: '/dashboard/best-sellers',
  payment: '/dashboard/payments',
  order: '/dashboard/order',
  media: '/dashboard/media',
  banner: '/dashboard/banner',
  user: '/dashboard/user',
  coupon: '/dashboard/coupon',
  feedback: '/dashboard/feedback',
  faq: '/dashboard/faq',
  faqCategory: '/dashboard/faq-category',
  blog: '/dashboard/blog',
  configuration: '/dashboard/configuration',
};

/**
 * These are the url paths for the backend apis that will be used in frontend
 */
export const endpoints = {
  login: '/auth/login',
  refresh: '/auth/refresh',
  register: '/auth/register',
  permission: '/permission',
  role: '/role',
  file: '/file',
  banner: '/banner',
  productCategory: '/product-category',
  productInterest: '/product-interest',
  productAge: '/product-age',
  productReview: '/product-review',
  product: '/product',
  user: '/user',
  productFilter: '/product/filters',
  cartItem: '/cart-item',
  dealOfTheDay: '/deal-of-the-day',
  feedback: '/feedback',
  configuration: '/configuration',
  coupon: '/coupon',
  order: '/order',
  faq: '/faq',
  faqCategory: '/faq-category',
  address: '/address',
  userOrders: '/order/user',
  payment: '/payment',
};

/**
 * These are the url paths for profile section in frontend
 */
export const profileRoutes = {
  login: '/login',
  signUp: '/sign-up',
  changePassword: '/profile/change-password',
  myOrder: '/profile/orders',
  address: '/profile/address',
  myProfile: '/profile',
  manageProfile: '/profile/manage',
};

export const navBarRoutesClient = {
  shopAll: '/shop-all',
  shopByAge: '/shop-by-age',
  shopByInterest: '/shop-by-interests',
  comboAndGifts: '/combo-gift-sets',
  ourStory: '/our-story',
  offers: '/offers',
  faq: '/faq',
  careers: '/careers',
  contactUs: '/contact-us',
  trackOrder: '/track',
  whyWollybee: '/why-wollybee',
  thankyou: '/thank-you',
  shopAllBestSellers: '/shop-all/best-sellers',
};

export const PERMISSION_METADATA_KEY = 'permissions';

export const MAX_FILE_UPLOAD_SIZE_LIMIT = 5 * 1024 * 1024;
export const MAX_FILE_UPLOAD_COUNT = 5;

export const CONFIGURATIONS = {
  FEEDBACK_OPTIONS: 'FEEDBACK_OPTIONS',
  SHIPPING_PRICE: 'SHIPPING_PRICE',
  FREE_SHIPPING_CART_VALUE: 'FREE_SHIPPING_CART_VALUE',
  YOUTUBE_LINK: 'YOUTUBE_LINK',
  ADVERTISEMENT_BANNER_HOMEPAGE: 'ADVERTISEMENT_BANNER_HOMEPAGE',
  CASH_ON_DELIVERY_CHARGES: 'CASH_ON_DELIVERY_CHARGES',
};

/**
 * Below Object contains all the desired permissions.
 */
export const permissions = {
  banner: {
    create: 'create:Banner:Banner',
    read: 'read:Banner:Banner',
    update: 'update:Banner:Banner',
    delete: 'delete:Banner:Banner',
  },
  coupon: {
    create: 'create:Coupon:Coupon',
    update: 'update:Coupon:Coupon',
    delete: 'delete:Coupon:Coupon',
  },
  product: {
    create: 'create:Product:Product',
    read: 'read:Product:Product',
    update: 'update:Product:Product',
    delete: 'delete:Product:Product',
  },
  role: {
    create: 'create:Role:Role',
    read: 'read:Role:Role',
    update: 'update:Role:Role',
    delete: 'delete:Role:Role',
  },
  productCategory: {
    create: 'create:Product:ProductCategory',
    read: 'read:Product:ProductCategory',
    update: 'update:Product:ProductCategory',
    delete: 'delete:Product:ProductCategory',
  },
  productAge: {
    create: 'create:Product:ProductAge',
    read: 'read:Product:ProductAge',
    update: 'update:Product:ProductAge',
    delete: 'delete:Product:ProductAge',
  },
  productInterest: {
    create: 'create:Product:ProductInterest',
    read: 'read:Product:ProductInterest',
    update: 'update:Product:ProductInterest',
    delete: 'delete:Product:ProductInterest',
  },
  user: {
    create: 'create:User:User',
    read: 'read:User:User',
    update: 'update:User:User',
    delete: 'delete:User:User',
  },
  configuration: {
    create: 'create:Configuration:Configuration',
    update: 'update:Configuration:Configuration',
    read: 'read:Configuration:Configuration',
  },
  dealOfTheDay: {
    create: 'create:DealOfTheDay:DealOfTheDay',
    read: 'read:DealOfTheDay:DealOfTheDay',
    update: 'update:DealOfTheDay:DealOfTheDay',
    delete: 'delete:DealOfTheDay:DealOfTheDay',
  },
  feedback: {
    read: 'read:Feedback:Feedback',
    update: 'update:Feedback:Feedback',
    delete: 'delete:Feedback:Feedback',
  },
  productReview: {
    create: 'create:ProductReview:ProductReview',
    read: 'read:ProductReview:ProductReview',
    update: 'update:ProductReview:ProductReview',
    delete: 'delete:ProductReview:ProductReview',
  },
  order: {
    read: 'read:Order:Order',
    update: 'update:Order:Order',
  },
  faqCategory: {
    create: 'create:Faq:FaqCategory',
    update: 'update:Faq:FaqCategory',
    delete: 'delete:Faq:FaqCategory',
  },
  faq: {
    create: 'create:Faq:Faq',
    update: 'update:Faq:Faq',
    delete: 'delete:Faq:Faq',
  },
  testimonial: {
    create: 'create:Testimonial:Testimonial',
    update: 'update:Testimonial:Testimonial',
    delete: 'delete:Testimonial:Testimonial',
  },
};

/**
 * Below Object contains all the static images for client.
 */
export const ICONS = {
  admin: {
    wollybeeLogoAndText: '/icons/wollybeeLogoAndText.svg',
    deleteIcon: '/icons/deleteIcon.svg',
    logoutIcon: '/icons/logoutIcon.svg',
    sideBarLogo: '/icons/sideBarLogo.svg',
  },
  carouselArrows: {
    grayLeft: '/arrows/grayLeft.svg',
    grayRight: '/arrows/grayRight.svg',
    grayThinBottom: '/arrows/grayThinBottom.svg',
    grayThinTop: '/arrows/grayThinTop.svg',
    whiteLeft: '/arrows/whiteLeft.svg',
    whiteRight: '/arrows/whiteRight.svg',
  },
  bottomNav: {
    shopAll: '/bottom-nav/shop-all.svg',
    categories: '/bottom-nav/categories.svg',
    giftHamper: '/bottom-nav/gift-hamper.svg',
    bestSeller: '/bottom-nav/best-seller.svg',
    shopAllWhite: '/bottom-nav/shop-all-active.svg',
    categoriesWhite: '/bottom-nav/categories-active.svg',
    giftHamperWhite: '/bottom-nav/gift-hamper-active.svg',
    bestSellerWhite: '/bottom-nav/best-seller-active.svg',
    shopAllActive: '/bottom-nav/shop-all-active-bg.svg',
    categoriesActive: '/bottom-nav/categories-active-bg.svg',
    giftHamperActive: '/bottom-nav/gift-hamper-active-bg.svg',
    bestSellerActive: '/bottom-nav/best-seller-active-bg.svg',
    navBarCurve: '/bottom-nav/navBarCurve.svg',
    navIcon: '/bottom-nav/navIcon.svg',
  },
  careersPage: {
    cloudCharacter: '/careerspage/cloudCharacterCareer.svg',
    girlWithRocket: '/careerspage/girlWithRocketCareer.svg',
    cultureImage: '/careerspage/cultureImage.svg',
    growthImage: '/careerspage/growthImage.svg',
    workLifeBalance: '/careerspage/workLifeBalance.svg',
  },
  contactUs: {
    kidsEvent: '/contact-us/kidsEvent.svg',
    workshops: '/contact-us/workshops.svg',
    brandCollaboration: '/contact-us/brandCollaboration.svg',
  },
  deliveryIcon: '/common/deliveryIcon.svg',
  returnIcon: '/common/returnIcon.svg',
  codAvailableIcon: '/common/codAvailableIcon.svg',
  myProfileIcon: '/icons/myProfileIcon.svg',
  footerStars: '/icons/FooterStars.svg',
  checkoutIcon: 'icons/checkoutIcons.svg',
  navbarIcon: '/icons/navbarIcon.svg',
  hamburgerIcon: '/icons/hamburgerIcon.svg',
  searchIcon: '/icons/searchIcon.svg',
  profileIcon: '/icons/profileIcon.svg',
  emptyCardIcon: '/icons/cartEmptyIcon.svg',
  fillCartIcon: '/icons/cartFillIcon.svg',
  wollyBeeLogoAndText: '/icons/wollybeeIconAndText.svg',
  instagramIcon: '/icons/instagramIcon.svg',
  hexagon: '/icons/hexagon.svg',
  santaDesktop: '/homepage/santaCharacter.svg',
  cloudWithSanta: '/backgrounds/cloudWithSanta.svg',
  footerCloud: '/backgrounds/footerCloud.svg',
  wollybeeFooterIcon: '/icons/wollybeeFooterIcon.svg',
  wollybeeFooterText: '/icons/wollybeeFooterText.svg',
  whatsappIcon: '/icons/whatsappIcon.svg',
  youtubeIcon: '/icons/youtubeIcon.svg',
  owlImage: '/homepage/owlImage.svg',
  cloud: '/backgrounds/choosePerfectGiftForm.svg',
  cloudMobile: '/backgrounds/choosePerfectGiftFormMobile.svg',
  boyCharacter: '/homepage/BoyLaying.svg',
  girlCharacter: '/homepage/GirlWithVictory.svg',
  hatCharacter: '/homepage/characterWithHat.svg',
  femalePanda: '/homepage/femalePanda.svg',
  cloudCarousel: '/homepage/ParentalZoneCarouselBackground.svg',
  shareIcon: '/icons/shareIcon.svg',
  decreaseCountIcon: '/icons/decrementIcon.svg',
  increaseCountIcon: '/icons/incrementIcon.svg',
  upCarouselArrow: '/icons/verticalCarouselUpIcon.svg',
  downCarouselArrow: '/icons/verticalCarouselDownIcon.svg',
  closeIcon: '/icons/closeIcon.svg',
  progressBarIcon: '/icons/progressBarIcon.svg',
  expandPlusIcon: '/icons/expandPlusIcon.svg',
  collapseMinusIcon: '/icons/collapseIcon.svg',
  backIcon: '/icons/backIcon.svg',
  wollybeeCheckoutLogo: '/icons/wollybeeCheckoutLogo.svg',
  rightArrowIcon: '/icons/rightArrowIcon.svg',
  careerHeroAnimation: './careerspage/animations/heroanimation.webm',
  contactHeroAnimation: './careerspage/animations/contactAnimation.svg',
  blogDealOfTheDay1: '/blogpage/deal-of-the-day-1.svg',
  blogDealOfTheDay2: '/blogpage/deal-of-the-day-2.svg',
  blogPageSingleOlin: '/blogpage/olin.svg',
  blogPageDemoImage: '/blogpage/blogdemo.svg',
  closeIconModal: '/icons/closeIconModal.svg',
  leftArrow: '/icons/leftArrow.svg',
  blueMonsterPlanet: '/our-story/blueMonsterPlanet.svg',
  earth: '/our-story/earth.svg',
  orangePlanet: '/our-story/orangePlanet.svg',
  rocketGirl: '/our-story/rocketGirl.svg',
  saturn: '/our-story/saturn.svg',
  mountains: '/our-story/mountains.svg',
  mountainsMobile: '/our-story/mountainsMobile.svg',
  stars: '/our-story/stars.svg',
  waveUpper: '/our-story/waveUpper.svg',
  waveLower: '/our-story/waveLower.svg',
  waveUpperMobile: 'our-story/waveUpperMobile.svg',
  founderImage: '/our-story/theFoundersDesktop.png',
  founderImageMobile: '/our-story/theFoundersMobile.png',
  greenWave: '/our-story/greenWave.svg',
  rocketGirlMobile: '/our-story/rocketGirlMobile.svg',
  whyWollybeeTree: '/backgrounds/whyCustomerTree.svg',
  whyWollybeeTreeMobile: '/why-wollybee/treeMobile.svg',
  characters: {
    babyQ: '/filters/babyQ.svg',
    kiloKangaroo: '/filters/kiloKangaroo.svg',
    ei: '/filters/ei.svg',
    olin: '/filters/olinOwl.svg',
    tonny: '/filters/tonnyTheMonny.svg',
    della: '/filters/dellaThePanda.svg',
  },
  shopByInterests: {
    creativity: '/filters/creativity.svg',
    earlyLearning: '/filters/earlyLearning.svg',
    empathy: '/filters/empathy.svg',
    math: '/filters/math.svg',
    reading: '/filters/reading.svg',
    scienceAndNature: '/filters/scienceAndNature.svg',
  },
  filterIcon: '/filters/filterIcon.svg',
  socials: {
    instagram: '/homepage/social/instagramIcon.svg',
    facebook: '/homepage/social/facebookIcon.svg',
    linkedin: '/homepage/social/linkedinIcon.svg',
    youtube: '/homepage/social/youtubeIcon.svg',
  },
  reviews: {
    reviewer1: '/homepage/reviews/aayshaSayed.jpg',
    reviewer2: '/homepage/reviews/devKumarVasudevan.jpg',
    reviewer3: '/homepage/reviews/tasneemAzad.jpg',
  },
  footerGirl: '/homepage/mobileFooterGirl.svg',
  shopAgeBoyPlaying: '/shop-by-age/boyPlaying.svg',
  shopAgeGirlPlaying: '/shop-by-age/girlPlaying.svg',
  shopAgeCloudPlaying: '/shop-by-age/cloudPlaying.svg',
  categoryCloudMobile: '/shop-by-age/categoryCloudMobile.svg',
  whyWollybee: {
    branch1: '/why-wollybee/branch1.svg',
    branch2: '/why-wollybee/branch2.svg',
    branch3: '/why-wollybee/branch3.svg',
    branch4: '/why-wollybee/branch4.svg',
    branch5: '/why-wollybee/branch5.svg',
    branch6: '/why-wollybee/branch6.svg',
    branch7: '/why-wollybee/branch7.svg',
    branchMobile6: '/why-wollybee/branchMobile6.svg',
    branchMobile7: '/why-wollybee/branchMobile7.svg',
    branch1Image: '/why-wollybee/branch1Image.svg',
    branch2Image: '/why-wollybee/branch2Image.svg',
    branch5Image: '/why-wollybee/branch5Image.svg',
    upperCloud: '/why-wollybee/upperCloud.svg',
    footer: '/why-wollybee/footer.svg',
    branch1Popup: '/why-wollybee/branch1Popup.svg',
    branch2Popup: '/why-wollybee/branch2Popup.svg',
    branch3Popup: '/why-wollybee/branch3Popup.svg',
    branch4Popup: '/why-wollybee/branch4Popup.svg',
    branch5Popup: '/why-wollybee/branch5Popup.svg',
    blueBird: '/why-wollybee/blueBird.svg',
    blueButterfly: '/why-wollybee/blueButterfly.svg',
    cloudBird: '/why-wollybee/cloudBird.svg',
    cloudButterfly: '/why-wollybee/cloudButterfly.svg',
    pinkBird: '/why-wollybee/pinkBird.svg',
    purpleBird: '/why-wollybee/purpleBird.svg',
    redBird: '/why-wollybee/redBird.svg',
    yellowBird: '/why-wollybee/yellowBird.svg',
    purpleMonster: '/why-wollybee/purpleMonster.svg',
    orangeMonster: '/why-wollybee/orangeMonster.svg',
    smallCloud1: '/why-wollybee/smallCloud1.svg',
    smallCloud2: '/why-wollybee/smallCloud2.svg',
    smallCloud3: '/why-wollybee/smallCloud3.svg',
    smallCloud4: '/why-wollybee/smallCloud4.svg',
    smallCloud5: '/why-wollybee/smallCloud5.svg',
    smallCloud6: '/why-wollybee/smallCloud6.svg',
    smallCloud7: '/why-wollybee/smallCloud7.svg',
    smallCloud8: '/why-wollybee/smallCloud8.svg',
    smallCloud9: '/why-wollybee/smallCloud9.svg',
    footerClouds: '/why-wollybee/footerClouds.svg',
    bushMobile1: '/why-wollybee/bushMobile1.svg',
    bushMobile2: '/why-wollybee/bushMobile2.svg',
    bushMobile3: '/why-wollybee/bushMobile3.svg',
    bushMobile4: '/why-wollybee/bushMobile4.svg',
    bushMobile5: '/why-wollybee/bushMobile5.svg',
    bushMobile6: '/why-wollybee/bushMobile6.svg',
    bushMobile7: '/why-wollybee/bushMobile7.svg',
  },
  profileArrowIcon: '/icons/profileArrowIcon.svg',
  addAddressIcon: '/icons/addAddressIcon.svg',
};

/**
 * Below array contains all the keywords used in SEO.
 */
export const keywords = [
  'best Educational Games in India',
  'educational toys for 5-6 year olds',
  'educational games for toddler',
  'educational games for 5 year olds',
  'learning games for 4 year olds',
  'learning games online',
  'learning games for 5 year olds',
  'educational games online',
  'learning games for kids free',
  'learn and play',
  'kids learning games',
  'learning games for 2 year olds',
  'games for two year olds',
  'best educational games for 3 year olds',
  'educational gifts for 7 year olds',
  'best educational games for 6 year olds',
  'fun games for 2 year olds',
  'best learning games for 2 year olds',
  'interactive games for 2 year olds',
  'games for 4 year olds at home',
  'interactive games for 4 year olds',
  'learning kits for 5 year olds',
  'best educational games for 7 year olds',
  'educational video games for 5 year olds',
  'interactive games for 6 year olds',
  'best educational games for 2 year olds',
  'learning gifts for 7 year olds',
  'educational things for 3 year olds',
];

export const whyCustomerData = [
  {
    id: '1',
    branch: ICONS.whyWollybee.branch1,
    image: ICONS.whyWollybee.branch1Image,
    title: 'Engaging & Educational',
    description:
      'Our colorful characters and interactive games make learning feel more like playtime, helping knowledge stick without a single tear or trick!',
    bushMobile: ICONS.whyWollybee.bushMobile1,
    bushColor: '#1E755B',
  },
  {
    id: '2',
    branch: ICONS.whyWollybee.branch2,
    image: ICONS.whyWollybee.branch2Image,
    title: 'Loveable Characters',
    description:
      'Our lovable characters from Bhollyland are relatable friends who your child can connect with. They learn, explore, and make mistakes, just like your little one. This fosters a sense of companionship and makes learning feel like a fun journey!',
    bushMobile: ICONS.whyWollybee.bushMobile2,
    bushColor: '#82B441',
  },
  {
    id: '3',
    branch: ICONS.whyWollybee.branch3,
    title: 'Fun for the Whole Family ',
    description:
      'Quality Time that Creates Memories; Wollybee products provide a perfect excuse to put down  phones and connect with your little ones. Laughter, the teamwork, and a sense of accomplishment – these are the ingredients for making precious memories that will last a lifetime. So, gather the and get ready for a fun-filled learning experience together!',
    bushMobile: ICONS.whyWollybee.bushMobile3,
    bushColor: '#4C8D43',
  },
  {
    id: '4',
    branch: ICONS.whyWollybee.branch4,
    title: 'Interactive Learning',
    description:
      'Ditch the passive learning experience and dive into the world of touch, feel, and explore! Wollybee products are designed to get little hands moving; every game is a hands-on adventure that engages multiple senses and keeps your child actively involved in the learning process..',
    bushMobile: ICONS.whyWollybee.bushMobile4,
    bushColor: '#82B249',
  },
  {
    id: '5',
    branch: ICONS.whyWollybee.branch5,
    image: ICONS.whyWollybee.branch5Image,
    title: 'Proven Results',
    description:
      "Happy Parents, Thriving Kids: We're proud of the countless positive reviews from parents who love seeing their children flourish with Wollybee, igniting a natural love of learning. Wollybee's playful approach to learning brings real results. Join our family and watch your child blossom into a curious,confident learner – all while having a blast! ",
    bushMobile: ICONS.whyWollybee.bushMobile5,
    bushColor: '#1E755B',
  },
];

export const socialLinks = {
  instagram: 'https://www.instagram.com/wollybeekids',
  facebook: 'https://www.facebook.com/wearewollybee',
  linkedin: 'https://www.linkedin.com/company/wollybee/',
  youtube: 'https://youtube.com/@wollybee',
  whatsapp: 'https://whatsapp.com/channel/0029VaCf2WDK5cDHyRxnqJ3d',
  whatsappChat: 'https://wa.me/917000413545',
};
