export enum OrderStatus {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
}

export enum OrderPaymentMode {
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  ONLINE = 'ONLINE',
  // CREDIT_CARD = 'CREDIT_CARD',
  // DEBIT_CARD = 'DEBIT_CARD',
  // NET_BANKING = 'NET_BANKING',
  // UPI = 'UPI',
  // WALLET = 'WALLET',
}
